"""Semantic stat definitions shared by scoring and presentation."""

from gd_affix_relevance.stats.registry import (
    PROFILE_TABS,
    RACE_STAT_SUFFIXES,
    RACE_DISPLAY_NAMES,
    RESISTANCE_STATS,
    PackageDefinition,
    StatDefinition,
    TabDefinition,
    all_stat_definitions,
    base_weapon_damage_stat,
    chance_damage_stat,
    conversion_stat,
    registered_stat_definitions,
    stat,
    stat_definition,
    stat_is_scoreable,
    stat_is_registered,
    validate_catalog,
)

__all__ = [
    "PROFILE_TABS",
    "RACE_STAT_SUFFIXES",
    "RACE_DISPLAY_NAMES",
    "RESISTANCE_STATS",
    "PackageDefinition",
    "StatDefinition",
    "TabDefinition",
    "all_stat_definitions",
    "base_weapon_damage_stat",
    "chance_damage_stat",
    "conversion_stat",
    "registered_stat_definitions",
    "stat",
    "stat_definition",
    "stat_is_scoreable",
    "stat_is_registered",
    "validate_catalog",
]
