"""Versioned compiled catalog models and loading."""

from gd_affix_relevance.catalog.models import (
    CATALOG_SCHEMA_VERSION,
    MAGNITUDE_CATALOG_FILE,
    AffixCatalog,
    AffixDefinition,
    AffixProperty,
    AffixTierDefinition,
    AffixVariantDefinition,
    CatalogBundle,
    CatalogManifest,
    ItemCatalog,
    ItemContainerSource,
    ItemDefinition,
    ItemMonsterSource,
    ItemProperty,
    ItemSkillModifier,
    ItemVendorSource,
    ItemVariantDefinition,
    MagnitudeBand,
    MagnitudeCatalog,
    MagnitudeEntry,
    MagnitudeProperty,
    SkillCatalog,
    SkillDefinition,
    StringCatalog,
)
from gd_affix_relevance.catalog.compiler import (
    CatalogCompileResult,
    compile_catalog_bundle,
)

__all__ = [
    "CATALOG_SCHEMA_VERSION",
    "MAGNITUDE_CATALOG_FILE",
    "AffixCatalog",
    "AffixDefinition",
    "AffixProperty",
    "AffixTierDefinition",
    "AffixVariantDefinition",
    "CatalogBundle",
    "CatalogCompileResult",
    "CatalogManifest",
    "ItemCatalog",
    "ItemContainerSource",
    "ItemDefinition",
    "ItemMonsterSource",
    "ItemProperty",
    "ItemSkillModifier",
    "ItemVendorSource",
    "ItemVariantDefinition",
    "MagnitudeBand",
    "MagnitudeCatalog",
    "MagnitudeEntry",
    "MagnitudeProperty",
    "SkillCatalog",
    "SkillDefinition",
    "StringCatalog",
    "compile_catalog_bundle",
]
