"""Versioned compiled catalog models and loading."""

from gd_affix_relevance.catalog.models import (
    CATALOG_SCHEMA_VERSION,
    MAGNITUDE_CATALOG_FILE,
    AffixCatalog,
    AffixDefinition,
    AffixProperty,
    AffixTierDefinition,
    AffixVariantDefinition,
    CatalogBundle,
    CatalogManifest,
    ItemCatalog,
    ItemContainerSource,
    ItemDefinition,
    ItemMonsterSource,
    ItemProperty,
    ItemSkillModifier,
    ItemVendorSource,
    ItemVariantDefinition,
    MagnitudeBand,
    MagnitudeCatalog,
    MagnitudeEntry,
    MagnitudeProperty,
    SkillCatalog,
    SkillDefinition,
    StringCatalog,
)
from gd_affix_relevance.catalog.compiler import (
    CatalogCompileResult,
    compile_catalog_bundle,
)
from gd_affix_relevance.catalog.locale_overlay import (
    EMPTY_OVERLAY,
    CatalogLocaleOverlay,
    load_catalog_locale_overlay,
    localize_affix_catalog,
    localize_catalog_bundle,
    localize_item_catalog,
    localize_skill_catalog,
)

__all__ = [
    "CATALOG_SCHEMA_VERSION",
    "MAGNITUDE_CATALOG_FILE",
    "EMPTY_OVERLAY",
    "AffixCatalog",
    "AffixDefinition",
    "AffixProperty",
    "AffixTierDefinition",
    "AffixVariantDefinition",
    "CatalogBundle",
    "CatalogCompileResult",
    "CatalogLocaleOverlay",
    "CatalogManifest",
    "ItemCatalog",
    "ItemContainerSource",
    "ItemDefinition",
    "ItemMonsterSource",
    "ItemProperty",
    "ItemSkillModifier",
    "ItemVendorSource",
    "ItemVariantDefinition",
    "MagnitudeBand",
    "MagnitudeCatalog",
    "MagnitudeEntry",
    "MagnitudeProperty",
    "SkillCatalog",
    "SkillDefinition",
    "StringCatalog",
    "compile_catalog_bundle",
    "load_catalog_locale_overlay",
    "localize_affix_catalog",
    "localize_catalog_bundle",
    "localize_item_catalog",
    "localize_skill_catalog",
]
